In [1]:
#!/usr/bin/python3

""" 
    Starter code for exploring the Enron dataset (emails + finances);
    loads up the dataset (pickled dict of dicts).

    The dataset has the form:
    enron_data["LASTNAME FIRSTNAME MIDDLEINITIAL"] = { features_dict }

    {features_dict} is a dictionary of features associated with that person.
    You should explore features_dict as part of the mini-project,
    but here's an example to get you started:

    enron_data["SKILLING JEFFREY K"]["bonus"] = 5600000
    
"""

' \n    Starter code for exploring the Enron dataset (emails + finances);\n    loads up the dataset (pickled dict of dicts).\n\n    The dataset has the form:\n    enron_data["LASTNAME FIRSTNAME MIDDLEINITIAL"] = { features_dict }\n\n    {features_dict} is a dictionary of features associated with that person.\n    You should explore features_dict as part of the mini-project,\n    but here\'s an example to get you started:\n\n    enron_data["SKILLING JEFFREY K"]["bonus"] = 5600000\n    \n'

In [2]:
import joblib

enron_data = joblib.load(open(r"D:\machine_learning\ud120-projects\final_project\final_project_dataset.pkl", "rb"))

The aggregated Enron email + financial dataset is stored in a dictionary, where each key in the dictionary is a person’s name and the value is a dictionary containing all the features of that person.
The email + finance (E+F) data dictionary is stored as a pickle file, which is a handy way to store and load python objects directly. Use datasets_questions/explore_enron_data.py to load the dataset.

**How many data points (people) are in the dataset?**

In [3]:
len(enron_data)

146

**For each person, how many features are available?**

In [4]:
import pandas as pd

df = pd.DataFrame.from_dict(enron_data, orient='index')

In [5]:
import numpy as np

df = df.replace('NaN', np.nan)

C:\Users\MO 2024\AppData\Local\Temp\ipykernel_15444\3763581521.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df = df.replace('NaN', np.nan)

In [6]:
df.shape

(146, 21)

In [7]:
df.head(3)

,salary,to_messages,deferral_payments,total_payments,loan_advances,bonus,email_address,restricted_stock_deferred,deferred_income,total_stock_value,...,from_poi_to_this_person,exercised_stock_options,from_messages,other,from_this_person_to_poi,poi,long_term_incentive,shared_receipt_with_poi,restricted_stock,director_fees
METTS MARK,365788.0,807.0,NaN,1061827.0,NaN,600000.0,mark.metts@enron.com,NaN,NaN,585062.0,...,38.0,NaN,29.0,1740.0,1.0,False,NaN,702.0,585062.0,NaN
BAXTER JOHN C,267102.0,NaN,1295738.0,5634343.0,NaN,1200000.0,NaN,NaN,-1386055.0,10623258.0,...,NaN,6680544.0,NaN,2660303.0,NaN,False,1586055.0,NaN,3942714.0,NaN
ELLIOTT STEVEN,170941.0,NaN,NaN,211725.0,NaN,350000.0,steven.elliott@enron.com,NaN,-400729.0,6678735.0,...,NaN,4890344.0,NaN,12961.0,NaN,False,NaN,NaN,1788391.0,NaN

The “poi” feature records whether the person is a person of interest, according to our definition. 

**How many POIs are there in the E+F dataset?**

In [8]:
df['poi'].value_counts()

poi
False    128
True      18
Name: count, dtype: int64

We compiled a list of all POI names (in ../final_project/poi_names.txt) and associated email addresses (in ../final_project/poi_email_addresses.py).

**How many POI’s were there total?** (Use the names file, not the email addresses, since many folks have more than one address and a few didn’t work for Enron, so we don’t have their emails.)

In [9]:
poi_names_path = r'D:\machine_learning\ud120-projects\final_project\poi_names.txt'
with open(poi_names_path, 'r') as f:
    total_people = sum(1 for line in f if line.strip().startswith('(y)') or line.strip().startswith('(n)'))

print("Total people listed in poi_names.txt:", total_people)

Total people listed in poi_names.txt: 35

Like any dict of dicts, individual people/features can be accessed like so:

enron_data["LASTNAME FIRSTNAME"]["feature_name"]
or, sometimes
enron_data["LASTNAME FIRSTNAME MIDDLEINITIAL"]["feature_name"]

**What is the total value of the stock belonging to James Prentice?**

In [10]:
df.loc['PRENTICE JAMES', 'total_stock_value']

np.float64(1095040.0)

Like any dict of dicts, individual people/features can be accessed like so:

enron_data["LASTNAME FIRSTNAME"]["feature_name"]

**How many email messages do we have from Wesley Colwell to persons of interest?**

In [11]:
df.loc['COLWELL WESLEY', 'from_this_person_to_poi']

np.float64(11.0)

Like any dict of dicts, individual people/features can be accessed like so:

enron_data["LASTNAME FIRSTNAME"]["feature_name"]

or

enron_data["LASTNAME FIRSTNAME MIDDLEINITIAL"]["feature_name"]

**What’s the value of stock options exercised by Jeffrey K Skilling?**

In [12]:
df.loc['SKILLING JEFFREY K', 'exercised_stock_options']

np.float64(19250000.0)

Of these three individuals (Lay, Skilling and Fastow), who took home the most money (largest value of “total_payments” feature)?

**How much money did that person get?**

In [13]:
df['total_payments'] = pd.to_numeric(df['total_payments'], errors='coerce').astype('Int64')

In [14]:
df.nlargest(5, 'total_payments')[['total_payments']]

                  total_payments
TOTAL                  309886585
LAY KENNETH L          103559793
FREVERT MARK A          17252530
BHATNAGAR SANJAY        15456290
LAVORATO JOHN J         10425757

For nearly every person in the dataset, not every feature has a value.

**How is it denoted when a feature doesn’t have a well-defined value?**

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 146 entries, METTS MARK to GLISAN JR BEN F
Data columns (total 21 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   salary                     95 non-null     float64
 1   to_messages                86 non-null     float64
 2   deferral_payments          39 non-null     float64
 3   total_payments             125 non-null    Int64
 4   loan_advances              4 non-null      float64
 5   bonus                      82 non-null     float64
 6   email_address              111 non-null    object
 7   restricted_stock_deferred  18 non-null     float64
 8   deferred_income            49 non-null     float64
 9   total_stock_value          126 non-null    float64
 10  expenses                   95 non-null     float64
 11  from_poi_to_this_person    86 non-null     float64
 12  exercised_stock_options    102 non-null    float64
 13  from_messages              86 non-null     float64
 14  other                      93 non-null     float64
 15  from_this_person_to_poi    86 non-null     float64
 16  poi                        146 non-null    bool
 17  long_term_incentive        66 non-null     float64
 18  shared_receipt_with_poi    86 non-null     float64
 19  restricted_stock           110 non-null    float64
 20  director_fees              17 non-null     float64
dtypes: Int64(1), bool(1), float64(18), object(1)
memory usage: 28.3+ KB

In [16]:
df.sample(5)

,salary,to_messages,deferral_payments,total_payments,loan_advances,bonus,email_address,restricted_stock_deferred,deferred_income,total_stock_value,...,from_poi_to_this_person,exercised_stock_options,from_messages,other,from_this_person_to_poi,poi,long_term_incentive,shared_receipt_with_poi,restricted_stock,director_fees
DIETRICH JANET R,250100.0,2572.0,NaN,1410464,NaN,600000.0,janet.dietrich@enron.com,NaN,NaN,1865087.0,...,305.0,1550019.0,63.0,473.0,14.0,False,556416.0,1902.0,315068.0,NaN
CLINE KENNETH W,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,-472568.0,NaN,189518.0,...,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN,662086.0,NaN
HERMANN ROBERT J,262663.0,NaN,NaN,1297461,NaN,700000.0,robert.hermann@enron.com,NaN,-280000.0,668132.0,...,NaN,187500.0,NaN,416441.0,NaN,False,150000.0,NaN,480632.0,NaN
YEAP SOON,NaN,NaN,NaN,55097,NaN,NaN,NaN,NaN,NaN,192758.0,...,NaN,192758.0,NaN,NaN,NaN,False,NaN,NaN,NaN,NaN
THE TRAVEL AGENCY IN THE PARK,NaN,NaN,NaN,362096,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,362096.0,NaN,False,NaN,NaN,NaN,NaN

**How many folks in this dataset have a quantified salary? What about a known email address?**

In [17]:
known_salary = df['salary'].notnull().sum()
known_email_address = df['email_address'].notnull().sum()
print("Number of people with a quantified salary:", known_salary)
print("Number of people with a known email address:", known_email_address)

Number of people with a quantified salary: 95
Number of people with a known email address: 111

As you saw a little while ago, not every POI has an entry in the dataset (e.g. Michael Krautz). That’s because the dataset was created using the financial data you can find in final_project/enron61702insiderpay.pdf, which is missing some POI’s (those absences propagated through to the final dataset). On the other hand, for many of these “missing” POI’s, we do have emails.

While it would be straightforward to add these POI’s and their email information to the E+F dataset, and just put “NaN” for their financial information, this could introduce a subtle problem. You will walk through that here.

**How many people in the E+F dataset (as it currently exists) have “NaN” for their total payments? What percentage of people in the dataset as a whole is this?**

In [18]:
unknown_total_payments = df['total_payments'].isnull().sum()
percentage_unknown_total_payments = (unknown_total_payments / df.shape[0]) * 100
print("Number of people with 'NaN' for total payments:", unknown_total_payments)
print("Percentage of people with 'NaN' for total payments:", percentage_unknown_total_payments,"%")

Number of people with 'NaN' for total payments: 21
Percentage of people with 'NaN' for total payments: 14.383561643835616 %

**How many POIs in the E+F dataset have “NaN” for their total payments? What percentage of POI’s as a whole is this?**

In [19]:
poi_with_nan_total_payments = df[(df['poi'] == True) & (df['total_payments'].isnull())].shape[0]
total_pois = df['poi'].sum()
percentage_poi_nan_total_payments = (poi_with_nan_total_payments / total_pois) * 100

print("Number of POIs with 'NaN' for total payments:", poi_with_nan_total_payments)
print("Percentage of POIs with 'NaN' for total payments:", percentage_poi_nan_total_payments, "%")

Number of POIs with 'NaN' for total payments: 0
Percentage of POIs with 'NaN' for total payments: 0.0 %

If you added in, say, 10 more data points which were all POI’s, and put “NaN” for the total payments for those folks, the numbers you just calculated would change.

**What is the new number of people of the dataset? What is the new number of folks with “NaN” for total payments?**

In [20]:
nan_mask = df['total_payments'].isna()

current_people = len(df)
current_nan_total_payments = int(nan_mask.sum())
current_POIs = int((df['poi'] == True).sum())

people_new = current_people + 10
nan_total_payments_new = current_nan_total_payments + 10
POIs_new = current_POIs + 10

people_new, nan_total_payments_new, POIs_new
print("New number of people in the dataset:", people_new
    ,"\nNew number of people with 'NaN' for total payments:", nan_total_payments_new
    ,"\nNew number of POIs in the dataset:", POIs_new
    )

New number of people in the dataset: 156
New number of people with 'NaN' for total payments: 31
New number of POIs in the dataset: 28

**What is the new number of POI’s in the dataset? What is the new number of POI’s with NaN for total_payments?**

In [21]:
POIs_nan_total_payments = int(((df['poi'] == True) & nan_mask).sum()) + 10

POIs_new, POIs_nan_total_payments
print("New number of POIs in the dataset:", POIs_new
    ,"\nNew number of POIs with 'NaN' for total payments:", POIs_nan_total_payments
    )

New number of POIs in the dataset: 28
New number of POIs with 'NaN' for total payments: 10